---
abstract: 'debug panel for Lazy Load Modules'
author:
  - 'Dai Okabayashi <bayashi@cpan.org>'
build_requires:
  HTTP::Request::Common: 0
  Plack: 0
  Test::More: 0.88
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-Debug-LazyLoadModules
provides:
  Plack::Middleware::Debug::LazyLoadModules:
    file: lib/Plack/Middleware/Debug/LazyLoadModules.pm
    version: 0.06
requires:
  Carp: 0
  Plack::Middleware::Debug: 0
  Plack::Util::Accessor: 0
  parent: 0
  perl: v5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/bayashi/Plack-Middleware-Debug-LazyLoadModules
version: 0.06
